/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.admin;

import app.MainGUI;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import lib.*;

/**
 *
 * @author ashda
 */
public class FormAddDoctor extends javax.swing.JFrame{

    JCheckBox[] daysOfWeekBoxes;
    
    DoctorFactory factory = new HISDoctorFactory();
    
    
    ArrayList <Account>  accounts;
    ArrayList <Doctor>   doct;
    ArrayList <Schedule> schedules = new ArrayList <Schedule>();

    
    Doctor d;
    Schedule s;
    Cardiologist cardio;
    Gastroentrologist gastro;
    
    int day;
    int numOfRows;
    String spec;
    
    int fHour;
    int fMin;
    int tHour;
    int tMin;

    
    /**
     * Creates new form AddDoctorForm
     */
    public FormAddDoctor() {
        initComponents();
       
        daysOfWeekBoxes = new JCheckBox[] {
            dMonday,   dTuesday, dWednesday, 
            dThursday, dFriday,  dSaturday,  dSunday,  
        };
        
//        specialization.addItem(cardio.getSpecialization());
//        specialization.addItem(gastro.getSpecialization());
    }
    
    public void setDoctors(ArrayList<Doctor> doctors) {
        this.doct = doctors;
    }
    
    public void setAccounts(ArrayList<Account> accounts) {
        this.accounts = accounts;
    }
   

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        inpFirstName = new javax.swing.JTextField();
        labSched = new javax.swing.JLabel();
        labFirstName1 = new javax.swing.JLabel();
        inpLastName = new javax.swing.JTextField();
        FromHour = new javax.swing.JSpinner();
        FromMinute = new javax.swing.JSpinner();
        labLastName1 = new javax.swing.JLabel();
        labSched1 = new javax.swing.JLabel();
        labSched2 = new javax.swing.JLabel();
        labSched3 = new javax.swing.JLabel();
        labSched4 = new javax.swing.JLabel();
        labSched5 = new javax.swing.JLabel();
        labSched6 = new javax.swing.JLabel();
        labSched7 = new javax.swing.JLabel();
        labSched8 = new javax.swing.JLabel();
        labSched9 = new javax.swing.JLabel();
        ToHour = new javax.swing.JSpinner();
        labSched10 = new javax.swing.JLabel();
        ToMinute = new javax.swing.JSpinner();
        labSpecialization = new javax.swing.JLabel();
        bSpecialization = new javax.swing.JComboBox<>();
        Doctor = new javax.swing.JButton();
        labLastName2 = new javax.swing.JLabel();
        labLastName3 = new javax.swing.JLabel();
        labLastName4 = new javax.swing.JLabel();
        dMonday = new javax.swing.JCheckBox();
        dTuesday = new javax.swing.JCheckBox();
        dWednesday = new javax.swing.JCheckBox();
        dThursday = new javax.swing.JCheckBox();
        dFriday = new javax.swing.JCheckBox();
        dSaturday = new javax.swing.JCheckBox();
        dSunday = new javax.swing.JCheckBox();
        labFirstName2 = new javax.swing.JLabel();
        inpUserName = new javax.swing.JTextField();
        labLastName5 = new javax.swing.JLabel();
        labLastName6 = new javax.swing.JLabel();
        inpPassword = new javax.swing.JPasswordField();

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("A Song of Ice and Fire");
        jLabel1.setMaximumSize(new java.awt.Dimension(168, 23));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medical Centre");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        panel2.setBackground(new java.awt.Color(0, 51, 153));
        panel2.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        panel3.setBackground(new java.awt.Color(255, 255, 255));
        panel3.setForeground(new java.awt.Color(255, 255, 255));

        inpFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpFirstNameActionPerformed(evt);
            }
        });

        labSched.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labSched.setText("Schedule:");

        labFirstName1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labFirstName1.setText("First Name:");

        inpLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpLastNameActionPerformed(evt);
            }
        });

        FromHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        FromMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        labLastName1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labLastName1.setText("Last Name:");

        labSched1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched1.setText(":\n");

        labSched2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched2.setText("M");

        labSched3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched3.setText("T");

        labSched4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched4.setText("W");

        labSched5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched5.setText("Th");

        labSched6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched6.setText("F");

        labSched7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched7.setText("Sa");

        labSched8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched8.setText("Su");

        labSched9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched9.setText("-");

        ToHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        labSched10.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labSched10.setText(":\n");

        ToMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        labSpecialization.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labSpecialization.setText("Specialization:");

        bSpecialization.setFont(new java.awt.Font("Yu Gothic Light", 0, 13)); // NOI18N
        bSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "Gastroentrology" }));
        bSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSpecializationActionPerformed(evt);
            }
        });

        Doctor.setBackground(new java.awt.Color(255, 255, 255));
        Doctor.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        Doctor.setText("Accept");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });

        labLastName2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labLastName2.setText("[ Day ]");

        labLastName3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labLastName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLastName3.setText("[ Time (24-Hour Format) ]");

        labLastName4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labLastName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLastName4.setText("[ Doctor Name ]");

        dMonday.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(dMonday);
        dMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dMondayActionPerformed(evt);
            }
        });

        dTuesday.setBackground(new java.awt.Color(255, 255, 255));
        dTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTuesdayActionPerformed(evt);
            }
        });

        dWednesday.setBackground(new java.awt.Color(255, 255, 255));
        dWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dWednesdayActionPerformed(evt);
            }
        });

        dThursday.setBackground(new java.awt.Color(255, 255, 255));
        dThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dThursdayActionPerformed(evt);
            }
        });

        dFriday.setBackground(new java.awt.Color(255, 255, 255));
        dFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dFridayActionPerformed(evt);
            }
        });

        dSaturday.setBackground(new java.awt.Color(255, 255, 255));
        dSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSaturdayActionPerformed(evt);
            }
        });

        dSunday.setBackground(new java.awt.Color(255, 255, 255));
        dSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSundayActionPerformed(evt);
            }
        });

        labFirstName2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labFirstName2.setText("User Name:");

        inpUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpUserNameActionPerformed(evt);
            }
        });

        labLastName5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labLastName5.setText("Password");

        labLastName6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labLastName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLastName6.setText("[ Doctor Log-in Info ]");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(labFirstName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inpFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addComponent(labLastName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(labFirstName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(labLastName5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inpPassword))
                            .addComponent(labLastName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(labLastName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 167, Short.MAX_VALUE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labLastName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                        .addComponent(labSpecialization)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bSpecialization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(labSched)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FromHour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labSched1)
                                        .addGap(2, 2, 2)
                                        .addComponent(FromMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labSched9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ToHour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(labSched10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ToMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labSched2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dMonday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labSched3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dTuesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labSched4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dWednesday)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labLastName2)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(labSched5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dThursday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labSched6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dFriday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labSched7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dSaturday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labSched8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dSunday)))
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Doctor)
                .addGap(345, 345, 345))
        );

        panel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labFirstName2, labLastName5});

        panel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labSched, labSpecialization});

        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labLastName4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labLastName6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(0, 46, Short.MAX_VALUE)
                                .addComponent(labLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labSched5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labSched6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labSched7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labSched8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labLastName3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FromHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labSched, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labSched1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FromMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labSched9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labSched10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labSched3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labSched4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dWednesday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dTuesday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labLastName5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dMonday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labSched2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Doctor)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static void writeDoctorsToCSV(ArrayList<Doctor> doctors) 
    {
        File outputCSV = new File("csvtest.csv");
    
        try (PrintWriter writer = new PrintWriter(outputCSV)) 
        {
            for(Doctor d : doctors) 
            {
                /**
                 * TODO: This 0, or 1, means that it's either a DOCTOR or a SCHEDULE
                 *       respectively, useful for when it comes to reading the file 
                 *       (see readDoctorsFromCSV) though I'm not sure if this is 
                 *       the best solution
                **/      
                writer.println("0," + 
                               d.getFirstName() + "," + 
                               d.getLastName()  + "," +
                               d.getConsultationRate()      + "," + 
                               d.getSpecialization());
                
                for(Schedule sched : d.getSchedules())
                {
                    writer.println("1," + sched.getDay() + "," +
                                    sched.getTimeFrom().getHourString()   + ":" +
                                    sched.getTimeFrom().getMinuteString() + "," +
                                    sched.getTimeTo().getHourString()     + ":" +
                                    sched.getTimeTo().getMinuteString()   + "," +
                                    (sched.isByAppointment() ? 1 : 0));
                }
            }
            
            System.out.println("Finished writing to " + outputCSV.getName());
        } catch(FileNotFoundException e) 
        {
            System.err.println("Error: File not found " + e.getMessage());
        }
    }
    
    private boolean validateInput() {
        return true;
    }
    
    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        if(validateInput()) {
            String firstName      = inpFirstName.getText();
            String lastName       = inpLastName.getText();
            String specialization = bSpecialization.getSelectedItem().toString();

            TimePoint timeFrom    = new TimePoint(Integer.parseInt(FromHour.getValue().toString()), 
                                                  Integer.parseInt(FromMinute.getValue().toString()));
            TimePoint timeTo      = new TimePoint(Integer.parseInt(ToHour.getValue().toString()), 
                                                  Integer.parseInt(ToMinute.getValue().toString()));

            for(int i = 0; i < daysOfWeekBoxes.length; ++i) {
                if(daysOfWeekBoxes[i].isSelected())
                    schedules.add(new Schedule(i, timeFrom, timeTo, false));
            }

            Doctor newDoct = factory.createDoctor(specialization, firstName, lastName, schedules);
            
            doct.add(newDoct);
            writeDoctorsToCSV(doct);
            
            // Create the doctor login account
            String userName   = inpUserName.getText();
            String password   = new String(inpPassword.getPassword());
            
            Account newAcc    = new Account(newDoct.getFirstName() + " " + newDoct.getLastName(), 
                                            userName, password, Account.DOCTOR);
            
            accounts.add(newAcc);
            MainGUI.writeAccountsToCSV(accounts, "accounts.csv");
            
            JOptionPane.showMessageDialog(null, "Successfully Added new doctor");
        }
    }//GEN-LAST:event_DoctorActionPerformed

    private void inpLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpLastNameActionPerformed

    private void inpFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpFirstNameActionPerformed

    }//GEN-LAST:event_inpFirstNameActionPerformed

    private void bSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSpecializationActionPerformed
//    int selectedIndex = bSpecialization.getSelectedIndex();
//        if (selectedIndex < bSpecialization.getItemCount()) {
//            bSpecialization.setSelectedIndex(selectedIndex + 1); 
//            
//        if  (selectedIndex == 0)
//            //spec = cardio.getSpecialization();
//            spec = "Cardiology";
//        else if  (selectedIndex == 1)
//            //spec = gastro.getSpecialization();
//            spec = "Gastroentrology";
        
//        }
    }//GEN-LAST:event_bSpecializationActionPerformed

    private void dMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dMondayActionPerformed
        
//        dMonday.setSelected(true);
//        if(dMonday.isSelected())
//        {
//            day = 1;
//            s.getDay();
//        }
    }//GEN-LAST:event_dMondayActionPerformed

    private void dTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTuesdayActionPerformed
        dTuesday.setSelected(true);
    }//GEN-LAST:event_dTuesdayActionPerformed

    private void dWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dWednesdayActionPerformed
        dWednesday.setSelected(true);
    }//GEN-LAST:event_dWednesdayActionPerformed

    private void dThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dThursdayActionPerformed
        dThursday.setSelected(true);
    }//GEN-LAST:event_dThursdayActionPerformed

    private void dFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dFridayActionPerformed
        dFriday.setSelected(true);
    }//GEN-LAST:event_dFridayActionPerformed

    private void dSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSaturdayActionPerformed
        dSaturday.setSelected(true);
    }//GEN-LAST:event_dSaturdayActionPerformed

    private void dSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSundayActionPerformed
        dSunday.setSelected(true);
    }//GEN-LAST:event_dSundayActionPerformed

    private void inpUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Doctor;
    private javax.swing.JSpinner FromHour;
    private javax.swing.JSpinner FromMinute;
    private javax.swing.JSpinner ToHour;
    private javax.swing.JSpinner ToMinute;
    private javax.swing.JComboBox<String> bSpecialization;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox dFriday;
    private javax.swing.JCheckBox dMonday;
    private javax.swing.JCheckBox dSaturday;
    private javax.swing.JCheckBox dSunday;
    private javax.swing.JCheckBox dThursday;
    private javax.swing.JCheckBox dTuesday;
    private javax.swing.JCheckBox dWednesday;
    private javax.swing.JTextField inpFirstName;
    private javax.swing.JTextField inpLastName;
    private javax.swing.JPasswordField inpPassword;
    private javax.swing.JTextField inpUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labFirstName1;
    private javax.swing.JLabel labFirstName2;
    private javax.swing.JLabel labLastName1;
    private javax.swing.JLabel labLastName2;
    private javax.swing.JLabel labLastName3;
    private javax.swing.JLabel labLastName4;
    private javax.swing.JLabel labLastName5;
    private javax.swing.JLabel labLastName6;
    private javax.swing.JLabel labSched;
    private javax.swing.JLabel labSched1;
    private javax.swing.JLabel labSched10;
    private javax.swing.JLabel labSched2;
    private javax.swing.JLabel labSched3;
    private javax.swing.JLabel labSched4;
    private javax.swing.JLabel labSched5;
    private javax.swing.JLabel labSched6;
    private javax.swing.JLabel labSched7;
    private javax.swing.JLabel labSched8;
    private javax.swing.JLabel labSched9;
    private javax.swing.JLabel labSpecialization;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
