/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.doctor;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import lib.Appointment;
import lib.Doctor;

/**
 *
 * @author UAFederez
 */
public class ViewAppointments extends javax.swing.JPanel {

    private static final SimpleDateFormat sdf        = new SimpleDateFormat("MMM-d-yyyy");
    private Doctor filter;
    private ArrayList<Appointment> appointments;
    private ArrayList<Appointment> matchedAppointments = new ArrayList<>();
    /**
     * Creates new form ViewAppointments
     */
    public ViewAppointments() {
        initComponents();
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setAppointments(ArrayList<Appointment> appointments) {
        this.appointments = appointments;
    }
    
    public void setDoctorFilter(Doctor doctor) {
        this.filter = doctor;
    }
    
    public Doctor getDoctorFilter() {
        return filter;
    }
    
    public JTable getAppointmentsTable() {
        return jTable1;
    }
    
     public Appointment getSelectedAppointment() {
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow != -1)
            return matchedAppointments.get(selectedRow);
        else
            return null;
    }

    
    public void refreshTable() {
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        
        tm.setRowCount(0);
        matchedAppointments.clear();
        
        for(Appointment appt : appointments) 
        {
            if(appt.getDoctor().equals(filter))
            {
                tm.addRow(new Object[] {
                    appt.getPatient().getFirstName(),
                    appt.getPatient().getLastName(),
                    sdf.format(appt.getDate()),
                    (appt.getTimeStart() != null ? appt.getTimeStart().getHourString() + ":" + appt.getTimeStart().getMinuteString(): 
                                                   "Not yet scheduled"),
                    appt.getNote()
                });
                
                matchedAppointments.add(appt);
            }
        }
        
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("View Appointments"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient First Name", "Patient Last Name", "Date of Appointment", "Time of Appointment", "Note"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
